export const FETCH_USER = 'FETCH_USER';

export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const CLICK_PLAYLIST = 'CLICK_PLAYLIST';
export const SET_TRACKS_NULL = 'SET_TRACKS_NULL';
export const SET_CLICKED_PLAYLIST_NULL = 'SET_CLICKED_PLAYLIST_NULL';
export const PROC_PLAYLIST_INIT = 'PROC_PLAYLIST_INIT';
export const SET_PROCESSED_PLAYLIST_NULL =
  'SET_PROCESSED_PLAYLIST_NULL';
